/*
  ARCHIVO DE PRODUCTOS — WarmaGames
  =================================
  IMPORTANTE: si configuraste un Google Sheet en config.js (campo
  SHEET_CSV), el catálogo usa los productos de esa hoja de cálculo y
  NO los de este archivo — este archivo queda como respaldo automático,
  por si el Google Sheet no carga por algún motivo.

  Si NO configuraste ningún Google Sheet, este es el archivo que se
  edita para agregar, quitar o cambiar productos.
  Cada producto es un bloque entre { llaves }.

  PARA AGREGAR UN PRODUCTO:
  1. Copia un bloque completo (desde { hasta la }, con la coma final).
  2. Pégalo antes del último ] (al final del archivo).
  3. Cambia los valores entre comillas por los del producto nuevo.
  4. Sube la foto a la carpeta /fotos y escribe su nombre en "imagen".
  5. Presiona "Commit changes". Espera 1-2 minutos y refresca la web.

  PARA QUITAR UN PRODUCTO: borra su bloque completo.
  PARA MARCARLO COMO AGOTADO: stock: "Agotado".
  PARA OCULTARLO SIN BORRARLO: mostrar: "No".

  CAMPOS:
  - id .......... código único, no se repite nunca.
  - nombre ...... como aparece en el catálogo.
  - categoria ... Rompecabezas / Juegos de mesa / Accesorios / Juguetes...
  - marca ....... fabricante.
  - piezas ...... solo el número (o vacío).
  - precio ...... solo el número, sin "Bs" (vacío = muestra "Consultar").
  - stock ....... "Disponible" o "Agotado".
  - imagen ...... nombre exacto del archivo dentro de /fotos.
  - imagenes .... fotos adicionales separadas por | (opcional).
  - descripcion . texto que aparece en la ficha del producto.
  - edad ........ edad recomendada (opcional).
  - tamano ...... medida del puzzle armado (opcional).
  - mostrar ..... "Si" o "No".

  Estos 149 productos salieron del catálogo de Navidad 2025 de WarmaGames
  (nombres, precios y fotos reales del PDF).
*/

window.PRODUCTOS = [
  {
    id: "WG-001",
    nombre: "Pokémon Edición Original",
    categoria: "Rompecabezas",
    marca: "Novelty",
    piezas: "1000",
    precio: "195",
    stock: "Disponible",
    imagen: "WG-001.jpg",
    imagenes: "WG-001-2.jpg",
    descripcion: "Rompecabezas de 1000 piezas de Novelty. Edad recomendada: 10+.",
    edad: "10+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-002",
    nombre: "Puzzle Mat · Tapete para armar hasta 2000 piezas",
    categoria: "Accesorios",
    marca: "Clementoni",
    piezas: "",
    precio: "195",
    stock: "Disponible",
    imagen: "WG-002.jpg",
    imagenes: "",
    descripcion: "Accesorio para armar rompecabezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-003",
    nombre: "Puzzle Sorter · Bandejas clasificadoras",
    categoria: "Accesorios",
    marca: "Clementoni",
    piezas: "",
    precio: "185",
    stock: "Disponible",
    imagen: "WG-003.jpg",
    imagenes: "",
    descripcion: "Accesorio para armar rompecabezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-004",
    nombre: "Classic Christmas Collection · Mercado navideño con carrusel",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "230",
    stock: "Disponible",
    imagen: "WG-004.jpg",
    imagenes: "WG-004-2.jpg|WG-004-3.jpg|WG-004-4.jpg",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 84,5x59,5 cm.",
    edad: "",
    tamano: "84,5x59,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-005",
    nombre: "Classic Christmas Collection · Papá Noel junto a la chimenea",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-005.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-006",
    nombre: "Classic Christmas Collection · Calle navideña con librería",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-006.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-007",
    nombre: "Classic Christmas Collection Panorama · Pueblo nevado con trineo",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-007.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-008",
    nombre: "Classic Christmas Collection Panorama · Carrusel en la plaza navideña",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-008.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-009",
    nombre: "Puzzle the Masterpiece · Puente de Brooklyn y Nueva York de noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "13200",
    precio: "1100",
    stock: "Disponible",
    imagen: "WG-009.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 13200 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-010",
    nombre: "High Quality Collection Panorama · Jardín fantástico con unicornio",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "",
    precio: "1100",
    stock: "Disponible",
    imagen: "WG-010.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-011",
    nombre: "High Quality Collection · Estante de jardín con libros y flores",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "6000",
    precio: "520",
    stock: "Disponible",
    imagen: "WG-011.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 6000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-012",
    nombre: "High Quality Collection · Las Vegas de noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "6000",
    precio: "520",
    stock: "Disponible",
    imagen: "WG-012.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 6000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-013",
    nombre: "High Quality Collection · Puente de Brooklyn al atardecer",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "6000",
    precio: "520",
    stock: "Disponible",
    imagen: "WG-013.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 6000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-014",
    nombre: "High Quality Collection · Londres, Big Ben y el Parlamento",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "330",
    stock: "Disponible",
    imagen: "WG-014.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-015",
    nombre: "High Quality Collection · Batalla de dragones submarinos",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "330",
    stock: "Disponible",
    imagen: "WG-015.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-016",
    nombre: "High Quality Collection · Terraza frente al puente de Brooklyn",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "330",
    stock: "Disponible",
    imagen: "WG-016.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-017",
    nombre: "High Quality Collection · Coliseo de Roma al atardecer",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "310",
    stock: "Disponible",
    imagen: "WG-017.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-018",
    nombre: "High Quality Collection · Nueva York, puente de Manhattan de noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "310",
    stock: "Disponible",
    imagen: "WG-018.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-019",
    nombre: "High Quality Collection · Torre Eiffel con jardín y cascadas",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "220",
    stock: "Disponible",
    imagen: "WG-019.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-020",
    nombre: "High Quality Collection · Montañas de China al amanecer",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "2000",
    precio: "240",
    stock: "Disponible",
    imagen: "WG-020.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 2000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-021",
    nombre: "High Quality Collection · Animales de la sabana en la charca",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "2000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-021.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 2000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-022",
    nombre: "High Quality Collection · Parque de atracciones de noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "2000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-022.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 2000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-023",
    nombre: "High Quality Collection · Paraíso tropical con cascadas",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "2000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-023.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 2000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-024",
    nombre: "High Quality Collection · Jardín mágico con búhos y castillo",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "220",
    stock: "Disponible",
    imagen: "WG-024.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 84,5x59,5 cm.",
    edad: "",
    tamano: "84,5x59,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-025",
    nombre: "High Quality Collection · Castillo de Neuschwanstein",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "220",
    stock: "Disponible",
    imagen: "WG-025.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 59,5x84,5 cm.",
    edad: "",
    tamano: "59,5x84,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-026",
    nombre: "Museum Collection · La noche estrellada",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "220",
    stock: "Disponible",
    imagen: "WG-026.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-027",
    nombre: "Museum Collection · Venecia, el Bucentauro",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-027.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-028",
    nombre: "Museum Collection · La Gioconda",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-028.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-029",
    nombre: "Museum Collection · La Torre de Babel",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "220",
    stock: "Disponible",
    imagen: "WG-029.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 84,5x59,5 cm.",
    edad: "",
    tamano: "84,5x59,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-030",
    nombre: "Museum Collection · La Transfiguración",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "220",
    stock: "Disponible",
    imagen: "WG-030.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 59,5x84,5 cm.",
    edad: "",
    tamano: "59,5x84,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-031",
    nombre: "Museum Collection · El beso de Hayez",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-031.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-032",
    nombre: "Museum Collection · Noche estrellada sobre el Ródano",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-032.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-033",
    nombre: "Museum Collection · El beso de Klimt",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-033.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-034",
    nombre: "Museum Collection · La Última Cena",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-034.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-035",
    nombre: "Museum Collection · La joven de la perla",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-035.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-036",
    nombre: "Museum Collection · Terraza de café por la noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-036.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-037",
    nombre: "Museum Collection · La caída de los ángeles rebeldes",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-037.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-038",
    nombre: "Museum Collection · La libertad guiando al pueblo",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "199",
    stock: "Disponible",
    imagen: "WG-038.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-039",
    nombre: "Museum Collection · En un café, La absenta",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "199",
    stock: "Disponible",
    imagen: "WG-039.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-040",
    nombre: "Museum Collection · La Virgen de las rocas",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "199",
    stock: "Disponible",
    imagen: "WG-040.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-041",
    nombre: "Museum Collection · Mujeres de Tahití",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-041.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-042",
    nombre: "Museum Collection · El almuerzo de los remeros",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-042.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-043",
    nombre: "Museum Collection · Van Gogh, Los girasoles",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-043.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-044",
    nombre: "High Quality Collection · Rueda del zodiaco",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-044.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-045",
    nombre: "High Quality Collection · Biblioteca invernadero con flamencos",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-045.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-046",
    nombre: "ColorBoom Collection · Ola de flores multicolor",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-046.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-047",
    nombre: "ColorBoom Collection · Collage en degradado arcoíris",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-047.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-048",
    nombre: "ColorBoom Collection · Selva fluorescente",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "140",
    stock: "Disponible",
    imagen: "WG-048.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni. Medida armado: 36x49 cm.",
    edad: "",
    tamano: "36x49 cm",
    mostrar: "Si"
  },
  {
    id: "WG-049",
    nombre: "High Quality Collection · Jardín japonés con el monte Fuji",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-049.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-050",
    nombre: "High Quality Collection Panorama · Manada de elefantes",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "199",
    stock: "Disponible",
    imagen: "WG-050.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-051",
    nombre: "High Quality Collection Panorama · Aurora boreal",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-051.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-052",
    nombre: "High Quality Collection · Tres cachorros labrador",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-052.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-053",
    nombre: "High Quality Collection · Jaguar entre la vegetación",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "140",
    stock: "Disponible",
    imagen: "WG-053.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni. Medida armado: 36x49 cm.",
    edad: "",
    tamano: "36x49 cm",
    mostrar: "Si"
  },
  {
    id: "WG-054",
    nombre: "High Quality Collection · Dos gatitos grises",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "140",
    stock: "Disponible",
    imagen: "WG-054.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-055",
    nombre: "DC Comics · Superman ante el Daily Planet",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-055.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-056",
    nombre: "DC Comics · Superman entre portadas de cómics",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-056.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-057",
    nombre: "DC Comics Batman Panorama",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-057.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-058",
    nombre: "DC Comics Impossible",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-058.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-059",
    nombre: "Disney Classics · Los Aristogatos",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-059.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-060",
    nombre: "Inside Out 2 · Super Color",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-060.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-061",
    nombre: "Marvel Spider-Man · Super Color",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-061.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-062",
    nombre: "Disney Stitch · Super Color",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "300",
    precio: "140",
    stock: "Disponible",
    imagen: "WG-062.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 300 piezas de Clementoni. Edad recomendada: 9+.",
    edad: "9+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-063",
    nombre: "Harry Potter · Set de 3 rompecabezas",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3x1000",
    precio: "399",
    stock: "Disponible",
    imagen: "WG-063.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3x1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-064",
    nombre: "Inside Out 2 · Super Color, burbujas de recuerdos",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-064.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-065",
    nombre: "Jurassic World",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-065.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Medida armado: 33,5x48,5 cm. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "33,5x48,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-066",
    nombre: "Jurassic World · Supercolor",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "180",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-066.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 180 piezas de Clementoni. Medida armado: 48,5x33,5 cm. Edad recomendada: 7+.",
    edad: "7+",
    tamano: "48,5x33,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-067",
    nombre: "High Quality Collection · Torre Eiffel iluminada de noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-067.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-068",
    nombre: "High Quality Collection · Duomo de Milán",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-068.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-069",
    nombre: "High Quality Collection · Santorini al atardecer",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-069.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-070",
    nombre: "High Quality Collection · Cataratas del Iguazú",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-070.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-071",
    nombre: "High Quality Collection Panorama · Cachorros beagle",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-071.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-072",
    nombre: "High Quality Collection Panorama · Venecia, el Gran Canal",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-072.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-073",
    nombre: "High Quality Collection · Nueva York de noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-073.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-074",
    nombre: "High Quality Collection Animals · Gatitos en el granero",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-074.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-075",
    nombre: "High Quality Collection · Volcán Etna en erupción",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-075.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-076",
    nombre: "High Quality Collection · Machu Picchu",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-076.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-077",
    nombre: "Panorama · Árbol solitario en un lago al atardecer",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-077.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-078",
    nombre: "High Quality Collection · Pirámides de Giza y la Esfinge",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-078.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-079",
    nombre: "High Quality Collection · Café de París con la Torre Eiffel",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-079.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni. Medida armado: 36x49 cm.",
    edad: "",
    tamano: "36x49 cm",
    mostrar: "Si"
  },
  {
    id: "WG-080",
    nombre: "High Quality Collection · Torre Eiffel desde el Sena",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-080.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni. Medida armado: 36x49 cm.",
    edad: "",
    tamano: "36x49 cm",
    mostrar: "Si"
  },
  {
    id: "WG-081",
    nombre: "Museum Collection · El Grito",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-081.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-082",
    nombre: "Museum Collection · Canaletto",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-082.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-083",
    nombre: "Disney · El Rey León",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-083.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-084",
    nombre: "Disney Classics · El Rey León",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-084.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-085",
    nombre: "Disney Winnie the Pooh · Super Color 3x48",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3x48",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-085.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3x48 piezas de Clementoni. Edad recomendada: 5+.",
    edad: "5+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-086",
    nombre: "Barbie · Super Color",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-086.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-087",
    nombre: "Barbie 10 en 1",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "10 en 1",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-087.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 10 en 1 piezas de Clementoni. Medida armado: 60x20 / 30x30 / 20x17 / 20x12 cm.",
    edad: "",
    tamano: "60x20 / 30x30 / 20x17 / 20x12 cm",
    mostrar: "Si"
  },
  {
    id: "WG-088",
    nombre: "Disney Stitch · Stitch surfeando",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-088.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Medida armado: 27x38 cm. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "27x38 cm",
    mostrar: "Si"
  },
  {
    id: "WG-089",
    nombre: "Disney Stitch · Castillo de arena en la playa",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-089.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni. Medida armado: 36x49 cm.",
    edad: "",
    tamano: "36x49 cm",
    mostrar: "Si"
  },
  {
    id: "WG-090",
    nombre: "Panorama · Disney Stitch en la fogata",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-090.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-091",
    nombre: "Disney Stitch · Stitch con proyector y fotos",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-091.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-092",
    nombre: "Panorama · Disney personajes multicolores",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-092.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-093",
    nombre: "Disney Mickey Mouse",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-093.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-094",
    nombre: "Marvel Captain America",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-094.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-095",
    nombre: "Panorama · Mickey y Minnie con fuegos artificiales",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-095.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-096",
    nombre: "Panorama · Disney Orquesta",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-096.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-097",
    nombre: "Disney Mickey Mouse Panorama",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-097.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-098",
    nombre: "Disney Villains Panorama",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-098.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-099",
    nombre: "Disney Alicia en el País de las Maravillas",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-099.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-100",
    nombre: "Peanuts · Snoopy y Charlie Brown en pastel",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-100.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-101",
    nombre: "Peanuts · Viñetas pop art de Snoopy",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-101.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-102",
    nombre: "Disney Princess",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-102.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-103",
    nombre: "Disney Donald Duck · Impossible",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-103.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-104",
    nombre: "Disney Frozen · Impossible",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-104.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-105",
    nombre: "Disney Villains · Villano con sombrero de copa",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "320",
    stock: "Disponible",
    imagen: "WG-105.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 84,5x59,5 cm.",
    edad: "",
    tamano: "84,5x59,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-106",
    nombre: "Tim Burton's The Nightmare Before Christmas",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-106.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-107",
    nombre: "Harry Potter Hogwarts",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-107.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-108",
    nombre: "Harry Potter · Personajes en tiras de película",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-108.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-109",
    nombre: "Harry Potter · Collage de objetos mágicos",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "320",
    stock: "Disponible",
    imagen: "WG-109.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 84,5x59,5 cm.",
    edad: "",
    tamano: "84,5x59,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-110",
    nombre: "DC · Impossible",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-110.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-111",
    nombre: "Batman Panorama",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-111.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-112",
    nombre: "Marvel · Impossible",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-112.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-113",
    nombre: "Marvel Spider-Man · Impossible",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-113.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 70x50 cm.",
    edad: "",
    tamano: "70x50 cm",
    mostrar: "Si"
  },
  {
    id: "WG-114",
    nombre: "Marvel Panorama",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-114.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 98x33 cm.",
    edad: "",
    tamano: "98x33 cm",
    mostrar: "Si"
  },
  {
    id: "WG-115",
    nombre: "Marvel Venom",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-115.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-116",
    nombre: "Marvel Studios Deadpool & Wolverine",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-116.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm. Edad recomendada: 14+.",
    edad: "14+",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-117",
    nombre: "High Quality Collection · Alicia en el País de las Maravillas",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-117.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni. Medida armado: 50x70 cm.",
    edad: "",
    tamano: "50x70 cm",
    mostrar: "Si"
  },
  {
    id: "WG-118",
    nombre: "More is More · Fashion & Design",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "240",
    stock: "Disponible",
    imagen: "WG-118.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-119",
    nombre: "More is More · Books & Writing",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "240",
    stock: "Disponible",
    imagen: "WG-119.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-120",
    nombre: "High Quality Collection · Jaguar",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "180",
    stock: "Disponible",
    imagen: "WG-120.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-121",
    nombre: "Disney Winnie the Pooh · Super Color 3x48",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3x48",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-121.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3x48 piezas de Clementoni. Edad recomendada: 5+.",
    edad: "5+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-122",
    nombre: "Disney Princess · Super Color",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-122.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-123",
    nombre: "Disney Junior Minnie · Super Color",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "104",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-123.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 104 piezas de Clementoni. Medida armado: 48,5x33,5 cm. Edad recomendada: 6+.",
    edad: "6+",
    tamano: "48,5x33,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-124",
    nombre: "Paw Patrol · Super Color",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "180",
    precio: "120",
    stock: "Disponible",
    imagen: "WG-124.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 180 piezas de Clementoni. Medida armado: 48,5x33,5 cm. Edad recomendada: 7+.",
    edad: "7+",
    tamano: "48,5x33,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-125",
    nombre: "Disney Junior Mickey",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "30",
    precio: "80",
    stock: "Disponible",
    imagen: "WG-125.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 30 piezas de Clementoni. Edad recomendada: 3+.",
    edad: "3+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-126",
    nombre: "High Quality Collection · Torre Eiffel",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "500",
    precio: "160",
    stock: "Disponible",
    imagen: "WG-126.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 500 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-127",
    nombre: "High Quality Collection · Barco pirata",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1500",
    precio: "220",
    stock: "Disponible",
    imagen: "WG-127.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1500 piezas de Clementoni. Medida armado: 59,5x84,5 cm.",
    edad: "",
    tamano: "59,5x84,5 cm",
    mostrar: "Si"
  },
  {
    id: "WG-128",
    nombre: "High Quality Collection · Velero Amerigo Vespucci",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "1000",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-128.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 1000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-129",
    nombre: "High Quality Collection · Orbis Terrarum, mapa antiguo",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "2000",
    precio: "240",
    stock: "Disponible",
    imagen: "WG-129.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 2000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-130",
    nombre: "High Quality Collection · Torre Eiffel de noche",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "2000",
    precio: "260",
    stock: "Disponible",
    imagen: "WG-130.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 2000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-131",
    nombre: "High Quality Collection · Mapa antiguo del mundo",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "280",
    stock: "Disponible",
    imagen: "WG-131.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-132",
    nombre: "High Quality Collection · San Francisco, tranvía al atardecer",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "280",
    stock: "Disponible",
    imagen: "WG-132.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-133",
    nombre: "High Quality Collection · Terraza sobre el lago",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "280",
    stock: "Disponible",
    imagen: "WG-133.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-134",
    nombre: "High Quality Collection · París, sueño con la Torre Eiffel",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "3000",
    precio: "320",
    stock: "Disponible",
    imagen: "WG-134.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 3000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-135",
    nombre: "High Quality Collection · Venecia al atardecer",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "6000",
    precio: "460",
    stock: "Disponible",
    imagen: "WG-135.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 6000 piezas de Clementoni.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-136",
    nombre: "Cubo mágico llavero tipo Ghost Cube",
    categoria: "Juguetes",
    marca: "",
    piezas: "",
    precio: "115",
    stock: "Disponible",
    imagen: "WG-136.jpg",
    imagenes: "",
    descripcion: "Juguete.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-137",
    nombre: "Sushi Go!",
    categoria: "Juegos de mesa",
    marca: "Devir",
    piezas: "",
    precio: "199",
    stock: "Disponible",
    imagen: "WG-137.jpg",
    imagenes: "",
    descripcion: "Juego de mesa de Devir. Edad recomendada: 8+.",
    edad: "8+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-138",
    nombre: "Mente Vacuna",
    categoria: "Juegos de mesa",
    marca: "Mercurio",
    piezas: "",
    precio: "270",
    stock: "Disponible",
    imagen: "WG-138.jpg",
    imagenes: "",
    descripcion: "Juego de mesa de Mercurio.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-139",
    nombre: "¿Alcachofas? ¡No, gracias!",
    categoria: "Juegos de mesa",
    marca: "Devir",
    piezas: "",
    precio: "190",
    stock: "Disponible",
    imagen: "WG-139.jpg",
    imagenes: "WG-139-2.jpg",
    descripcion: "Juego de mesa de Devir. Edad recomendada: 10+.",
    edad: "10+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-140",
    nombre: "Fantasma Blitz",
    categoria: "Juegos de mesa",
    marca: "Devir",
    piezas: "",
    precio: "250",
    stock: "Disponible",
    imagen: "WG-140.jpg",
    imagenes: "",
    descripcion: "Juego de mesa de Devir.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-141",
    nombre: "Science & Play LAB · Dinosaurs, kit de excavación",
    categoria: "Juguetes",
    marca: "Clementoni",
    piezas: "",
    precio: "99",
    stock: "Disponible",
    imagen: "WG-141.jpg",
    imagenes: "",
    descripcion: "Juguete de Clementoni. Edad recomendada: 7+.",
    edad: "7+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-142",
    nombre: "Barbie 10 en 1 · Supercolor",
    categoria: "Rompecabezas",
    marca: "Clementoni",
    piezas: "10 en 1",
    precio: "150",
    stock: "Disponible",
    imagen: "WG-142.jpg",
    imagenes: "",
    descripcion: "Rompecabezas de 10 en 1 piezas de Clementoni. Medida armado: 60x20 / 30x30 / 20x17 / 20x12 cm.",
    edad: "",
    tamano: "60x20 / 30x30 / 20x17 / 20x12 cm",
    mostrar: "Si"
  },
  {
    id: "WG-143",
    nombre: "Rhino Hero Super Battle",
    categoria: "Juegos de mesa",
    marca: "",
    piezas: "",
    precio: "450",
    stock: "Disponible",
    imagen: "WG-143.jpg",
    imagenes: "",
    descripcion: "Juego de mesa.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-144",
    nombre: "Unstable Unicorns · 2ª Edición",
    categoria: "Juegos de mesa",
    marca: "",
    piezas: "",
    precio: "60",
    stock: "Disponible",
    imagen: "WG-144.jpg",
    imagenes: "",
    descripcion: "Juego de mesa. Edad recomendada: 8+. Versión réplica.",
    edad: "8+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-145",
    nombre: "Virus! Marvel",
    categoria: "Juegos de mesa",
    marca: "Tranjis Games",
    piezas: "",
    precio: "60",
    stock: "Disponible",
    imagen: "WG-145.jpg",
    imagenes: "",
    descripcion: "Juego de mesa de Tranjis Games. Edad recomendada: 8+. Versión réplica.",
    edad: "8+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-146",
    nombre: "Virus!",
    categoria: "Juegos de mesa",
    marca: "Tranjis Games",
    piezas: "",
    precio: "60",
    stock: "Disponible",
    imagen: "WG-146.jpg",
    imagenes: "",
    descripcion: "Juego de mesa de Tranjis Games. Edad recomendada: 8+. Versión réplica.",
    edad: "8+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-147",
    nombre: "Virus! 2 · Expansión",
    categoria: "Juegos de mesa",
    marca: "Tranjis Games",
    piezas: "",
    precio: "45",
    stock: "Disponible",
    imagen: "WG-147.jpg",
    imagenes: "",
    descripcion: "Juego de mesa de Tranjis Games. Versión réplica.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-148",
    nombre: "Exploding Kittens · Edición Original",
    categoria: "Juegos de mesa",
    marca: "",
    piezas: "",
    precio: "60",
    stock: "Disponible",
    imagen: "WG-148.jpg",
    imagenes: "",
    descripcion: "Juego de mesa. Edad recomendada: 7+. Versión réplica.",
    edad: "7+",
    tamano: "",
    mostrar: "Si"
  },
  {
    id: "WG-149",
    nombre: "Taco Gato Cabra Queso Pizza",
    categoria: "Juegos de mesa",
    marca: "Buró",
    piezas: "",
    precio: "60",
    stock: "Disponible",
    imagen: "WG-149.jpg",
    imagenes: "WG-149-2.jpg",
    descripcion: "Juego de mesa de Buró. Versión réplica.",
    edad: "",
    tamano: "",
    mostrar: "Si"
  }
];
